### ISSUE TITLE
Watch folder with subfolders

### ISSUE THREAD

**Issue by quant235** [djaydev/docker-recordings-transcoder#4]
Hi,

at first I would like to thank you for this great software.
The video files within my watch folder are located in several subfolders. It seems that the software does not recognize them, because the transcoding does not start. Is there any way I can keep the subfolder structure and use the automatic transcoder at the same time?

Best regards

**Comment by djaydev** [comment]
Hey,
Thank you, I hope after we get it working you'll enjoy the software.

The software does work with sub folders but I have received messages in the past about special characters in the folder or file names.  Can you please send me the full path of one or two of the recordings that didn't work?
 For example /home/user/videos/fun_shows/funniest_show_season1/episode1.ts

Also, please start the container and let it try to convert, and after a few minutes capture the docker logs and paste them here. You can get the docker logs from the command line by running: 
`docker logs <container's name here>`

**Comment by quant235** [comment]
Your tip really helped me, because now I have found out that it is due to the umlauts in the file name. My paths included german umlauts like ä, ü and ö. After changing the filenames, the automatic transcoding works fine. Do you know if there is a workaround to deal with those umlauts?
Thank you for your very quick and helpful response 👍

**Comment by djaydev** [comment]
I believe this issue has something to do with locales but unfortunately I'm not quite sure how to fix it.  Try adding the following docker variable to the docker container and let me know if it works.

`-e LANG=C.UTF-8`

**Comment by quant235** [comment]
Adding this variable unfortunately did not resolve the problem. However, there is an error message related to this behaviour:
"/run/s6/services/autovideoconverter/autovideoconverter: line 250: basename: unbound variable".
I have just added the "skip any unsafe characters" option in my recorder software and it's working now.
