### ISSUE TITLE
Really nice to add comskip and comchap after the convert

### ISSUE THREAD

**Issue by chacawaca** [djaydev/docker-recordings-transcoder#5]
I really like this docker, it would be perfect for my need if you can add comskip and comchap after the convert, to only tag chapter and create a .edl file.

**Comment by djaydev** [comment]
I have a docker container you can use for comskip located at https://hub.docker.com/r/djaydev/auto-comskip .  

I'm not familiar with Comchap or .edl files, but you can contact the creator of this docker located at https://hub.docker.com/r/mezz64/comskip since it mentions comskip + comchap
