### ISSUE TITLE
DELETE_TS =1 not working

### ISSUE THREAD

**Issue by chacawaca** [djaydev/docker-recordings-transcoder#6]
DELETE_TS seem to not work at all. I only have to put 1 in my setting and it should delete my .ts ?

**Comment by chacawaca** [comment]
I tried to use $CONVERSION_STATUS in post_conversion.sh  to delete file but, successful or not, $CONVERSION_STATUS=1 every time.

**Comment by chacawaca** [comment]
after some test, if i set AUTOMATED_CONVERSION_KEEP_SOURCE=0, that work

**Comment by chacawaca** [comment]
i use custom script for encode, and in 02-setvariable.sh, i think if you set custom, delete_ts do nothing.

**Comment by djaydev** [comment]
DELETE_TS =1 adds the shell command "rm video.ts" and it works.  I run it on my main server and it works on my test servers.

**Comment by chacawaca** [comment]
look at this file 02-setvariable.sh, if you have a custom.sh you never set $ENCODER_SCRIPT  and $ENCODER_SCRIPT_END
 i dont see how it can work.

**Comment by djaydev** [comment]
If you have custom.sh, then you need to include your wishes in your custom.sh, including the delete.  The options like DELETE_TS =1 is if you're not using custom.
