### ISSUE TITLE
Enable usage of x264|vp9|whatever

### ISSUE THREAD

**Issue by chrissi5120** [djaydev/docker-recordings-transcoder#7]
Hi,

it would make a ton of sense to enable the selection of different codecs via parameter like this:

CODEC=X264

each supported codec could then have a specific call inside the script (example on software.sh):

CODEC_USED=${CODEC}
X264="ffmpeg -i "$1" -hide_banner -loglevel info -max_muxing_queue_size 512 -c:v libx264 -brand mp42 -ac 2 -c:a libfdk_aac -b:a 128k "$map/$mp4""

best regards

Christoph

**Comment by chrissi5120** [comment]
Hi @djaydev,

do you have an example for the custom config?

I would like to try it out

best regards

Christoph

**Comment by djaydev** [comment]
The container is just a set of scripts, and the software FFmpeg to convert videos.
The 1st script looks for ".ts" files in the /watch folder for you automatically.  You cannot customize this part of the process.

The 2nd script is kicked off once the 1st script finds a ".ts".  This is where you want to create a custom script to use FFmpeg however you want.  FFmpeg is command line interface by default so if you're not familiar with it you can get started here https://ffmpeg.org/ffmpeg.html.

Like we mentioned in a previous post, to utilize a custom script first place the script file in /config and name it "custom.sh".  Lastly in the docker run command change the variable "ENCODER" to "custom". 

As an example, you mentioned using X264 codec with FFmpeg.  Here's an untested sample script file.

```
#!/bin/bash
LogFile=/config/log/postProcess.$date.log
IFS=$(echo -en "\n\b")
export LD_LIBRARY_PATH=/usr/local/lib
mkv="$(basename $1)"
map="$(dirname $1)"
mp4="${mkv%.*}.mp4"
mp4="$(basename $mp4)"
exec 3>&1 1>>${LogFile} 2>&1
ffmpeg -i "$1" -hide_banner -loglevel info -max_muxing_queue_size 512 -c:v libx264 -ac 2 -c:a libfdk_aac -b:a 128k "$map/$mp4
```
