### ISSUE TITLE
Intel transcoding for a i9-10900?

### ISSUE THREAD

**Issue by johnny2678** [djaydev/docker-recordings-transcoder#8]
added `--device /dev/dri:/dev/dri`to extra parameters and `modprobe i915` to the go file

but the container fails with `docker: Error response from daemon: error gathering device information while adding custom device "/dev/dri": no such file or directory.`

Doesn't look like I have a `/dev/dri/`

I'll prob be ok with the software option, but wanted to check if you had any ideas?

thx a lot for this.

**Comment by djaydev** [comment]
Since you mentioned the go file, it sounds like you are using Unraid.  The current version of Unraid 6.8.3 is using a kernel that does not have support for the I9-10900's iGPU.  You can try the beta Unraid version Tools -> Update OS -> change branch to next.  I haven't tested it myself, but that Unraid beta version should have the kernel you need to use the i9-10900.

**Comment by johnny2678** [comment]
Hi thx.  I'm on Unraid 6.9.0b25.  Is the modprobe command (`modprobe i915`) the same?

**Comment by djaydev** [comment]
yes `modprobe i915` needs to added to the go file, if it wasn't there at boot you'll need to reboot the server.  After that go to Unraid's terminal and type `ls /dev/dri`

Should look similar to this:
```
root@unraid:~# ls /dev/dri
by-path/  card0  renderD128
root@unraid:~# 
```

**Comment by johnny2678** [comment]
odd... I did reboot after modding the go file, but still no `/dev/dri`

```
root@15620-BEAST:/mnt/user/appdata# more /boot/config/go 
#!/bin/bash
# Start the Management Utility
/usr/local/sbin/emhttp &

#sensor chip drivers
modprobe coretemp
modprobe nct6775
modprobe i915

root@15620-BEAST:/mnt/user/appdata# ls /dev/dri
/bin/ls: cannot access '/dev/dri': No such file or directory
```

Not asking you to spend a ton of time on this.  Currently transcoding happily with your container using the software setting.  Just wanted to reach out in case I was missing something.

**Comment by djaydev** [comment]
From what I can find on the internet, Unraid 6.9.0b25 is using kernel 5.7.8 which supports Intel's 10000 CPU+iGPUs.  The only other thing I can think of is make sure your 10900 isn't the "F" model, because that model doesn't have an iGPU built in.  [https://ark.intel.com/content/www/us/en/ark/products/199329/intel-core-i9-10900f-processor-20m-cache-up-to-5-20-ghz.html](url)

Just thought of another, make sure the iGPU is turned on in the motherboard's bios.  If it's off there, it's never exposed to the OS.  Every motherboard uses different names/options to do this, but here's an example on an ASUS motherboard.

![image](https://user-images.githubusercontent.com/33335484/93026077-4b637280-f5d1-11ea-9654-3138735010d4.png)

**Comment by johnny2678** [comment]
thx again, yea it's just the 10900 model that does have the 630 UHD Graphics.  Not the F version

https://ark.intel.com/content/www/us/en/ark/products/199328/intel-core-i9-10900-processor-20m-cache-up-to-5-20-ghz.html

I'm pretty sure the GPU is enabled in the bios.  Will triple check at the next reboot.

**Comment by djaydev** [comment]
Here's a popular guide on the Unraid forums [https://forums.unraid.net/topic/77943-guide-plex-hardware-acceleration-using-intel-quick-sync/](url)

One interesting note in that thread is having something connected to the HDMI port on the motherboard before the iGPU is active.

"3. Compatible Motherboard

You will need to enable iGPU on your motherboard BIOS

In some cases this may require you to have the HDMI output plugged in and connected to a monitor in order for it to be active.

If you find that this is the case on your setup you can buy a dummy HDMI doo-dad that tricks your unRAID box into thinking that something is plugged in."

**Comment by johnny2678** [comment]
ok, now I just feel bad that you're googling things for me 😂

There is an hdmi cable connected to the MB currently.

I'll do some more research on linux and GPUs.  Gotta be some simple troubleshooting guides I can follow to get it to show.

Thx again for the support.

Container is awesome btw.

**Comment by djaydev** [comment]
> There is an hdmi cable connected to the MB currently.

Not just a cable, but a monitor or something else (or you can buy a dummy HDMI doo-dad) because there has to be an electrical connection.  The cable alone is just like the port being empty.  You probably already know that just making sure.

Also, got a another idea, in the Unraid WebUI go to tools -> System Devices -> "PCI Devices and IOMMU Groups" section, in that area you should see an entry for the intel iGPU.  Mine says "IOMMU group 1: | [8086:3ea5] 00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics 655 (rev 01)" and yours will be something similar.

If you don't see an entry for VGA controller, then the bios isn't exposing it to Unraid after boot.  If it is there, Unraid isn't loading the kernel module/driver so that it shows under /dev/dri.

**Comment by johnny2678** [comment]
ok, you did it.  and I feel foolish

when I followed your suggestion to look at the IOMMU Groups, I realized that I had assigned the Intel GPU for virtualization early on in my build.  I haven't actually set up any VMs so I didn't think of this but obviously it was putting a lock on the device.  
Removed the assignment and rebooted and now /dev/dri is there.

and OMG is it fast.  Under 5% CPU utilization and it's just flying through recordings.  Going to have to watch a recording to make sure it's actually doing it.

thank you again for the support.

**Comment by djaydev** [comment]
I have multiple generations of Intel CPUs w/ iGPUs, the only thing I can think of is that library is out of date.  I'm running an update to the container to see if it pulls a newer version.  I'll let you know when it finishes.

**Comment by djaydev** [comment]
While we wait for the build to finish, one possible issue could be permissions on the iGPU. 

Go to the Unraid terminal and type: `chmod -R 777 /dev/dri`
Go to the appdata/recordings-converter folder and the delete the file named "failed_conversions"
restart the recordings-converter

**Comment by johnny2678** [comment]
hmm, I have the chmod cmd in my go file.

just tried to run it manually and restarted the container but still failing.

Same error when I run a manual ffmpeg

`ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory`

this is my Unraid /dev/dri

```
root@15620-BEAST:/mnt/user/appdata/recordings-converter# ls -la /dev/dri
total 0
drwxrwxrwx  3 root root       100 Sep 14 11:15 ./
drwxr-xr-x 16 root root      4040 Sep 14 11:18 ../
drwxrwxrwx  2 root root        80 Sep 14 11:15 by-path/
crwxrwxrwx  1 root video 226,   0 Sep 14 11:15 card0
crwxrwxrwx  1 root video 226, 128 Sep 14 11:15 renderD128

```

Just forced a `apt-get update/upgrade` inside the container and the results changed a bit

```
root@9ae5cd4c3b67:/tmp# ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i "/watch/kids/Curious George (2006)/Season 01/Curious George (2006) - S01E12 - Doctor Monkey; Curious George the Architect.ts" -vf 'format=nv12|vaapi,hwupload,deinterlace_vaapi' -c:v hevc_vaapi -brand mp42 -ac 2 -c:a libfdk_aac -b:a 128k "/watch/test.mp4"    
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x55d02ec37580] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x55d02ec37580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
root@9ae5cd4c3b67:/tmp# 
```

Still looks like an issue mapping /dev/dri but it is mapped in the container:
```
root@9ae5cd4c3b67:/tmp# ls -la /dev/dri
total 0
drwxr-xr-x 2 root root                80 Sep 14 17:56 .
drwxr-xr-x 6 root root               360 Sep 14 17:56 ..
crwxrwxrwx 1 root videoCAKqLcjZ 226,   0 Sep 14 17:56 card0
crwxrwxrwx 1 root videoCAKqLcjZ 226, 128 Sep 14 17:56 renderD128
root@9ae5cd4c3b67:/tmp# 
```

**Comment by djaydev** [comment]
Oh so first you can't run the ffmpeg command directly like that, because the export for the library folder isn't included.  

Really the easiest way is to send me the log files from appdata/recordings-converter/log

These logs files will better describe why the conversion is failing

P.S. if you really want to run the ffmpeg command like that in the docker's console, do it like this:
`export LD_LIBRARY_PATH=/usr/local/lib && ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i "/watch/kids/Curious George (2006)/Season 01/Curious George (2006) - S01E12 - Doctor Monkey; Curious George the Architect.ts" -vf 'format=nv12|vaapi,hwupload,deinterlace_vaapi' -c:v hevc_vaapi -brand mp42 -ac 2 -c:a libfdk_aac -b:a 128k "/watch/test.mp4"`

**Comment by johnny2678** [comment]
looks like the same error from the logs:

```
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --ena
ble-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-l
ibx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3
 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x5590e88bf580] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x5590e88bf580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --ena
ble-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-l
ibx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3
 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x55fd85125580] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x55fd85125580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error

```
Same from a manual run exporting `LD_LIBRARY_PATH`:
```
root@9ae5cd4c3b67:/tmp# export LD_LIBRARY_PATH=/usr/local/lib && ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -i "/watch/kids/Curious George (2006)/Season 01/Curious George (2006) - S01E12 - Doctor Monkey; Curious George the Architect.ts" -vf 'format=nv12|vaapi,hwupload,deinterlace_vaapi' -c:v hevc_vaapi -brand mp42 -ac 2 -c:a libfdk_aac -b:a 128k "/watch/test.mp4"
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[AVHWDeviceContext @ 0x56384ddbf580] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x56384ddbf580] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
root@9ae5cd4c3b67:/tmp# 
```

the `by-path` folder in /dev/dri doesn't seem to be visible in the container.  Not sure why but could that be a problem?

**Comment by johnny2678** [comment]
a little out of my league here, but according to redditers, intel is not supporting vaapi in Comet Lake? https://www.reddit.com/r/jellyfin/comments/hfy3ot/stumped_with_hw_transcoding/

**Comment by djaydev** [comment]
The update has finished, try it out :)

Go to the appdata/recordings-converter folder and the delete the file named "failed_conversions"
update the recordings-converter
send me the log files from appdata/recordings-converter/log

**Comment by johnny2678** [comment]
ok, pulled the latest, cleared failed recordings and the logs

Same error:

```
root@15620-BEAST:/mnt/user/appdata/recordings-converter/log# more postProcess.14-09-2020-1832.log 
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --ena
ble-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-l
ibx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3
 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[AVHWDeviceContext @ 0x558ad93835c0] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x558ad93835c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --ena
ble-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-l
ibx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3
 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[AVHWDeviceContext @ 0x5611572e55c0] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x5611572e55c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
root@15620-BEAST:/mnt/user/appdata/recordings-converter/log# 
```

I'm leaning towards a permissions issue still but not sure how to address if `chmod -R 777 /dev/dri` is already in my go file

**Comment by djaydev** [comment]
You can verify the permissions in the container console with 
```root@50c19e5ad0cc:/tmp# ls /dev/dri -la
total 0
drwxr-xr-x 2 root root                80 Sep 14 18:26 .
drwxr-xr-x 6 root root               360 Sep 14 18:26 ..
crw-rw---- 1 root videokPkpkdAB 226,   0 Sep 14 18:26 card0
crwxrwxrwx 1 root videokPkpkdAB 226, 128 Sep 14 18:26 renderD128
```

My guess is the driver inside the container from Ubuntu.  I have a coffee lake intel and a few older, a user on the Unraid forums has a 9900k, this is first 10900 I've tried to get working.

**Comment by johnny2678** [comment]
yea, might be a comet lake thing.

Happy to test any other ideas but it's 7pm here and football just started ;) don't want to waste any more of your evening.

**Comment by djaydev** [comment]
Took a bit but I think I may have stumbled upon the issue.

Please go to the console of the docker container and type:
```
apt update
apt install intel-media-va-driver -y
```

Let me know if that works, ***fingers crossed***

**Comment by johnny2678** [comment]
hmmm... still a libva error but it's slightly different this time after adding the `intel-media-va-driver`

```
root@15620-BEAST:/mnt/user/appdata/recordings-converter/log# more postProcess.15-09-2020-0818.log 
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-vaapi --enable-nvenc --enable-cuvid --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --ena
ble-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-l
ibx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3
 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec' --extra-ldflags=-L/opt/ffmpeg/lib --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[AVHWDeviceContext @ 0x558ffa3d05c0] libva: No valid vtable entry for vaPutSurface
[AVHWDeviceContext @ 0x558ffa3d05c0] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x558ffa3d05c0] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[AVHWDeviceContext @ 0x558ffa3d05c0] Failed to initialise VAAPI connection: -1 (unknown libva error).
Device creation failed: -5.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Input/output error
Error parsing global options: Input/output error
```

**Comment by djaydev** [comment]
Well I believe this is as far as I can get until Ubuntu/Debian updates the libva package in their repositories.  It's fixed on libva's github page with a PR [https://github.com/intel/libva/pull/401](url) 

Your iGPU has to use the iHD driver that's installed with `intel-media-va-driver` but the error below causes it fail, it's removed in the pull request I linked above.  On my system, I get the same two lines for the first errors, but my iGPU can use the i965 driver so I don't get the third failed error message.

> [AVHWDeviceContext @ 0x558ffa3d05c0] libva: No valid vtable entry for vaPutSurface
> [AVHWDeviceContext @ 0x558ffa3d05c0] libva: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
> [AVHWDeviceContext @ 0x558ffa3d05c0] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init faile

**Comment by johnny2678** [comment]
That's some major league internet sleuthing! I'll keep doing periodic apt updates to see if this ever gets pushed.

**Comment by djaydev** [comment]
I built a test docker image you can try based on Alpine instead of Ubuntu.  I'm pretty sure it'll work based on my results on my system.

If you want to try it out:
Go to docker webUI settings page for recordings-converter and change "Repository: "to "djaydev/recordings-converter:alpine"
Set "Include subtitles " to "0"
You know the rest, delete failed conversions, etc.

**Comment by johnny2678** [comment]
progress... sort of.  GPU transcoding is definitely happening on this branch.

good old alpine.  ~6% cpu utilization down from ~60% with software converting, and smaller image size to boot.

I am seeing some errors maybe they are media related? I was tailing the log file watching the fps when I caught an error on my first transcoded file. Mp4 was created but won't play:
```
root@15620-BEAST:/mnt/user/appdata/recordings-converter/log# tail -F postProcess.15-09-2020-1006.log -n 100
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-vulkan --enable-libaom --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mpegts, from '/watch/kids/Daniel Tigers Neighborhood (2012)/Season 02/Daniel Tiger's Neighborhood (2012) - S02E17 - Daniel Makes a Mistake; Baking Mistakes.ts':
  Duration: 00:29:58.75, start: 1.400000, bitrate: 7336 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(tv, top first), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Side data:
      cpb: bitrate max/min/avg: 80000000/0/0 buffer size: 7995392 vbv_delay: N/A
    Stream #0:1[0x101](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, 5.1(side), fltp, 384 kb/s
    Stream #0:2[0x102](spa): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, mono, fltp, 128 kb/s
    Stream #0:3[0x103](eng): Audio: ac3 ([129][0][0][0] / 0x0081), 48000 Hz, mono, fltp, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (native) -> hevc (hevc_vaapi))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[hevc_vaapi @ 0x558ef3084d80] No quality level set; using default (25).
Output #0, mp4, to '/watch/kids/Daniel Tigers Neighborhood (2012)/Season 02/Daniel Tiger's Neighborhood (2012) - S02E17 - Daniel Makes a Mistake; Baking Mistakes.mp4':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: hevc (hevc_vaapi) (Main) (hev1 / 0x31766568), vaapi_vld, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 29.97 fps, 30k tbn, 29.97 tbc
    Metadata:
      encoder         : Lavc58.91.100 hevc_vaapi
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac
[AVHWFramesContext @ 0x558ef3053600] Failed to sync surface 0x5: 23 (internal decoding error).0 speed=2.28x    
[mpeg2video @ 0x558ef30ee040] Failed to transfer data to output frame: -5.
Error while processing the decoded data for stream #0:0
[aac @ 0x558ef3086240] Qavg: 414.847
[aac @ 0x558ef3086240] 2 frames left in the queue on closing
Conversion failed!
```

second one converted successfully and plays fine.

third one failed for the same reason the first one did:
```
[AVHWFramesContext @ 0x55a90da22480] Failed to sync surface 0x4: 23 (internal decoding error).0 speed= 2.2x    
[mpeg2video @ 0x55a90d8dc2c0] Failed to transfer data to output frame: -5.
Error while processing the decoded data for stream #0:0
[aac @ 0x55a90d8f10c0] Qavg: 456.181
[aac @ 0x55a90d8f10c0] 2 frames left in the queue on closing
Conversion failed!
```

The source files are getting deleted (not a big deal) so I need to stop and change the flag to keep files. If some of my content is getting GPU converted it's better than nothing.  Will do some further tests to see if the files that failed can be converted using CPU.

You've put in Yeoman's work on this.  thx again.

**Comment by djaydev** [comment]
Man this one's hard!  

Never seen that ffmpeg error in my life, apparently neither has google. I do think that's an issue with the original video file but that's just guess. ` stream #0:0` is definitely the video portion of the file. 

Sorry about the deleting of the source videos, I run a check to make sure the new file exists and it's not just an empty file before deleting the original one.  That has usually prevented unwanted deletes but this is a new error that seems to create enough of a new video file to make it look like it worked.

**Comment by johnny2678** [comment]
If you haven't figured out by now, most of these recordings are kids shows ;) I'm not really worried about it.

But in a future update, maybe look for `Conversion failed!` in the log before deleting?

I'm not really sure how to do a pull request but I could take a stab at this when i have some time.  No need to burden you with it.

**Comment by johnny2678** [comment]
Flipped back to CPU/software transcoding but I don't have the failed source files to check so will just monitor going forward.  Was at at least a 50% failure rate with GPU.

Something I guess i wasn't aware of is CPU/software transcoding is much faster on my rig (~2.5x).  In my current situation I'm trying to convert a backlog about about 900GB .ts files.

Might just leave it on CPU until the backlog has completed and then flip back to GPU transcoding.

**Comment by djaydev** [comment]
>  maybe look for Conversion failed!
Oh if you know how to fix this then please help!

If you don't know the PR process just a attach a text file here and I'll credit you. Or read up on it here https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by johnny2678** [comment]
This command parses the latest log file and returns a count of occurrences of `Conversion failed!`.  Don't have any more time but dropping it here so I don't forget.

Next step for me is to figure out where in the `run` file we can do an `if` statement to check this.
 
```
more `ls -Art $LOG_DIR | tail -n 1`| grep -c 'Conversion failed!'
```

**Comment by djaydev** [comment]
Thank you for all your contributions!

The way the current delete original .ts works is it just checks if the new .mp4 file exists and that there's some file size to it. This check is iside the /scripts/*.sh files, not the run file.

```
if [ -f "$map/$mp4" ] && [ -s "$map/$mp4" ] ; then
rm "$1"
```

I'd be happy to change it though, make it more accurate.  If we only use the option for just conversion failed, if the script fails before that ffmpeg message, say during ccextractor, that message won't exist in the logs.  So I think that we still need to check if there's a file at `$map/$mp4` as well as if the log file contains conversion failed.
